<?xml version="1.0" encoding="UTF-8"?><schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:dataleveransebasertpasosidatamodell="https://skjema.geonorge.no/SOSI/produktspesifikasjon/skredfaresoner/dataleveranse-basert-pa-sosi-datamodell/1.0" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:sc="http://www.interactive-instruments.de/ShapeChange/AppInfo" elementFormDefault="qualified" targetNamespace="https://skjema.geonorge.no/SOSI/produktspesifikasjon/skredfaresoner/dataleveranse-basert-pa-sosi-datamodell/1.0" version="1.0">
  <import namespace="http://www.interactive-instruments.de/ShapeChange/AppInfo" schemaLocation="https://shapechange.net/resources/schema/ShapeChangeAppinfo.xsd"/>
  <import namespace="http://www.opengis.net/gml/3.2" schemaLocation="http://schemas.opengis.net/gml/3.2.1/gml.xsd"/>
  <!--XML Schema document created by ShapeChange - http://shapechange.net/-->
  <element name="Analyseområde" substitutionGroup="dataleveransebasertpasosidatamodell:SkredFareområderFellesegenskaper" type="dataleveransebasertpasosidatamodell:AnalyseområdeType">
    <annotation>
      <documentation>dekning av et område analysert med tanke på potensiell skredfare</documentation>
    </annotation>
  </element>
  <complexType name="AnalyseområdeType">
    <complexContent>
      <extension base="dataleveransebasertpasosidatamodell:SkredFareområderFellesegenskaperType">
        <sequence>
          <element name="område" type="gml:SurfacePropertyType">
            <annotation>
              <documentation>objektets utstrekning

-- Definition --
area over which an object extends</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">Flate</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element maxOccurs="unbounded" name="analyseområdeGrense" type="dataleveransebasertpasosidatamodell:AnalyseområdeGrPropertyType"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="AnalyseområdePropertyType">
    <sequence minOccurs="0">
      <element ref="dataleveransebasertpasosidatamodell:Analyseområde"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <element name="AnalyseområdeGr" substitutionGroup="gml:AbstractFeature" type="dataleveransebasertpasosidatamodell:AnalyseområdeGrType">
    <annotation>
      <documentation>avgrensningslinje for område analysert med tanke på potensiell skredfare</documentation>
    </annotation>
  </element>
  <complexType name="AnalyseområdeGrType">
    <complexContent>
      <extension base="gml:AbstractFeatureType">
        <sequence>
          <element name="grense" type="gml:CurvePropertyType">
            <annotation>
              <documentation>forløp som følger overgang mellom ulike fenomener

-- Definition --
course following the transition between different real world phenomena</documentation>
            </annotation>
          </element>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="AnalyseområdeGrPropertyType">
    <sequence minOccurs="0">
      <element ref="dataleveransebasertpasosidatamodell:AnalyseområdeGr"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <element name="Identifikasjon" substitutionGroup="gml:AbstractObject" type="dataleveransebasertpasosidatamodell:IdentifikasjonType"/>
  <complexType name="IdentifikasjonType">
    <sequence>
      <element name="lokalId" type="string">
        <annotation>
          <documentation>lokal identifikator, tildelt av dataleverendør/dataforvalter. Den lokale identifikatoren er unik innenfor navnerommet, ingen andre objekter har samme identifikator.

NOTE: Det er data leverendørens ansvar å sørge for at denne lokale identifikatoren er unik innenfor navnerommet.</documentation>
          <appinfo>
            <sc:taggedValue tag="SOSI_navn">LOKALID</sc:taggedValue>
          </appinfo>
        </annotation>
      </element>
      <element name="navnerom" type="string">
        <annotation>
          <documentation>navnerom som unikt identifiserer datakilden til objektet, starter med to bokstavs kode jfr ISO 3166. Benytter understreking  ("_") dersom data produsenten ikke er assosiert med bare et land.

NOTE 1 : Verdien for nanverom vil eies av den dataprodusent som har ansvar for de unike identifikatorene og vil registreres i "INSPIRE external  Object Identifier Namespaces Register"

Eksempel: NO for Norge.</documentation>
          <appinfo>
            <sc:taggedValue tag="SOSI_navn">NAVNEROM</sc:taggedValue>
          </appinfo>
        </annotation>
      </element>
      <element minOccurs="0" name="versjonId" type="string">
        <annotation>
          <documentation>identifikasjon av en spesiell versjon av et geografisk objekt (instans), maksimum lengde på 25 karakterers. Dersom spesifikasjonen av et geografisk objekt med en identifikasjon inkludererer livsløpssyklusinformasjon, benyttes denne versjonId for å skille mellom ulike versjoner av samme objekt. versjonId er en unik  identifikasjon av versjonen.

NOTE Maksimum lengde er valgt for å tillate tidsregistrering i henhold til  ISO 8601, slik som  "2007-02-12T12:12:12+05:30" som versjonId.</documentation>
          <appinfo>
            <sc:taggedValue tag="SOSI_navn">VERSJONID</sc:taggedValue>
          </appinfo>
        </annotation>
      </element>
    </sequence>
  </complexType>
  <complexType name="IdentifikasjonPropertyType">
    <sequence>
      <element ref="dataleveransebasertpasosidatamodell:Identifikasjon"/>
    </sequence>
  </complexType>
  <element name="Kartleggingsområde" substitutionGroup="gml:AbstractFeature" type="dataleveransebasertpasosidatamodell:KartleggingsområdeType">
    <annotation>
      <documentation>dekning av et område kartlagt med tanke på potensiell skredfare</documentation>
    </annotation>
  </element>
  <complexType name="KartleggingsområdeType">
    <complexContent>
      <extension base="gml:AbstractFeatureType">
        <sequence>
          <element name="område" type="gml:SurfacePropertyType">
            <annotation>
              <documentation>objektets utstrekning</documentation>
            </annotation>
          </element>
          <element minOccurs="0" name="kartleggingsområdeID" type="string">
            <annotation>
              <documentation>kartleggingsområdets identifikator</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">KARTLEGGINGSOMRÅDEID</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element minOccurs="0" name="kartleggingsområdeNavn" type="string">
            <annotation>
              <documentation>navn på kartleggingsområde</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">KARTLEGGINGSOMRÅDENAVN</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element minOccurs="0" name="kartleggingStatus" type="dataleveransebasertpasosidatamodell:Prosjektstatus_NVEType">
            <annotation>
              <documentation>Status for kartleggingen av aktuelt område</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">KARTLEGGINGSTATUS</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element maxOccurs="unbounded" name="områdekant" type="dataleveransebasertpasosidatamodell:KartleggingsområdekantPropertyType"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="KartleggingsområdePropertyType">
    <sequence minOccurs="0">
      <element ref="dataleveransebasertpasosidatamodell:Kartleggingsområde"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <element name="Kartleggingsområdekant" substitutionGroup="gml:AbstractFeature" type="dataleveransebasertpasosidatamodell:KartleggingsområdekantType">
    <annotation>
      <documentation>avgrensningslinje for et kartleggingsområde som dekker et nærmere angitt geografisk område.</documentation>
    </annotation>
  </element>
  <complexType name="KartleggingsområdekantType">
    <complexContent>
      <extension base="gml:AbstractFeatureType">
        <sequence>
          <element name="grense" type="gml:CurvePropertyType">
            <annotation>
              <documentation>forløp som følger overgang mellom ulike fenomener</documentation>
            </annotation>
          </element>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="KartleggingsområdekantPropertyType">
    <sequence minOccurs="0">
      <element ref="dataleveransebasertpasosidatamodell:Kartleggingsområdekant"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <element abstract="true" name="KvikkleireFaresone" substitutionGroup="dataleveransebasertpasosidatamodell:SkredFareområderFellesegenskaper" type="dataleveransebasertpasosidatamodell:KvikkleireFaresoneType">
    <annotation>
      <documentation>areal med evaluering av risiko for kvikkleireskred basert på skadekonsekvens og faregrad

Merknad: Kvikkleiresonene inndeles deretter i 5 "risikoklasser" basert på skadekonsekvensen og faregraden


-- Definition --
area which has been reviewed for quick clay slide hazard based on damage consequences and degree of hazard</documentation>
    </annotation>
  </element>
  <complexType abstract="true" name="KvikkleireFaresoneType">
    <complexContent>
      <extension base="dataleveransebasertpasosidatamodell:SkredFareområderFellesegenskaperType">
        <sequence>
          <element name="område" type="gml:SurfacePropertyType">
            <annotation>
              <documentation>objektets utstrekning

-- Definition --
area over which an object extends</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">Flate</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element name="skredOmrID" type="integer">
            <annotation>
              <documentation>unikt id-nummer for skredområde/kvikkleirefaresone

-- Definition --
unique ID number for landslide area or quick clay hazard zone</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">SKREDOMRID</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element minOccurs="0" name="skredOmrNavn" type="string">
            <annotation>
              <documentation>stedsnavn som brukes i forbindelse med en skredhendelse

-- Definition --
place name which is used in connection with a landslide event</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">SKREDOMRNAVN</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element minOccurs="0" name="arealKm2" type="double">
            <annotation>
              <documentation>faresonens areal i kvadratkilometer (km2)</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">AREAL_KM2</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element name="skredFaregradKlasse" type="dataleveransebasertpasosidatamodell:SkredFaregradKlasseType">
            <annotation>
              <documentation>graden av sannsynlighet for at det skal gå et skred

Merknad: Gjenspeiler graden av usikkerhet med hensyn til områdets stabilitet basert på topografiske forhold, geologiske/geotekniske forhold og erosjonsforhold. Skredfaregradklassen er for skredtypen kvikkleire basert på en evaluering av faregrad som fremkommer av at ulike vektede faktorer gir en faregradscore (0-51)

-- Definition --
the degree of probability that there will be a landslide
Note: Reflects the degree of hazard as regards the area's stability,, based upon topographic conditions, geological/geotechnical conditions and erosion conditions. For quick clay landslides the landslideHazardLevelClass is based upon a weighed hazardfactorscore (0-51)</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">SKREDFAREGR_KL</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element minOccurs="0" name="skredSkadeKonsekvensScore" type="integer">
            <annotation>
              <documentation>poengverdi basert på vektede faktorer for skadekonsekvensen

Merknad: Se nærmere definisjon i kap. definisjoner og forkortelser.

-- Definition --
value (in points) based on weighted factors for the consequences of damage   Note: See more precise definition in chapter on definitions and abbreviations.</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">SKREDKONSSCORE</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element minOccurs="0" name="skredRisikoKvikkleireKlasse" type="dataleveransebasertpasosidatamodell:SkredRisikoKvikkleireKlasseType">
            <annotation>
              <documentation>risikoen for at et område kan bli påført skredskade, inndelt etter risikoklasser

Merknad: Denne egenskapen gjengir en klassifisering av risiko for at området vil bli utsatt for skredskade. Klassifiseringsmetoden er basert på en evaluering av skadekonsekvens og faregrad. Evalueringen foretas ved at det beregnes poeng for hver sone i henhold til utarbeidde klassifiseringskriterier (se kapittel definisjoner og forkortelser)

-- Definition --
the risk that a landslide may inflict damage on an area, categorized according to risk classes   Note: This attribute cites a classification of risk that the area will be vulnerable to landslide damage. The classification method is based on a review of damage consequences and hazard levels</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">SKREDRISIKO_KL</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element name="skredKvalKartlegging" type="dataleveransebasertpasosidatamodell:SkredKvalKartleggingType">
            <annotation>
              <documentation>angir status og detaljeringsgrad  når det gjelder kartlegging av sonen

-- Definition --
indicates the status and degree of detail as regards the mapping of the zone</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">SKREDKVALKARTLEGGING</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element minOccurs="0" name="skredFaregradScore" type="integer">
            <annotation>
              <documentation>tallverdi som er fremkommet ved at de viktigste kriteriene og faktorene som påvirker faregraden for kvikkleireskred er vurdert (jfr. Tabell 2 under kap.definisjoner og forkortelser.)

-- Definition --
numerical value which results from the evaluation of the influence of the most important criteria and factors on the degree of hazard of a quick clay slide (cf. Table 2 in the chapter on definitions and abbreviations.)</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">SKREDFAREGRADSCORE</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element minOccurs="0" name="skredSkadeKonsekvensKlasse" type="dataleveransebasertpasosidatamodell:SkredSkadeKonsekvensKlasseType">
            <annotation>
              <documentation>hvilke økonomiske og samfunnsmessige følger et kvikkleireskred får og fare for tap av menneskeliv

Merknad: Kvalitativ klassifisering av skadekonsekvens i forbindelse med fare for liv, skade på mennesker, økonomiske tap, verdiforringelse samt fare for at viktige samfunnsmessige funksjoner skal stoppe opp.  For skredtypen kvikkleire er inndelingen basert på beregningen av en poengverdi basert på vektede faktorer (se kap. definisjoner og forkortelser.) i kombinasjon med skadekonsekvensen

-- Definition --
what economic and social consequences follow a quick clay slide, and risk of loss of human lives   Note: Qualitative classification of consequences of damage in connection with risk of fatalities, personal injuries, financial loss, value reduction as well as the risk that important social functions can be affected</documentation>
            </annotation>
          </element>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="KvikkleireFaresonePropertyType">
    <sequence minOccurs="0">
      <element ref="dataleveransebasertpasosidatamodell:KvikkleireFaresone"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <element name="KvikkleireFaresoneAvgr" substitutionGroup="gml:AbstractFeature" type="dataleveransebasertpasosidatamodell:KvikkleireFaresoneAvgrType">
    <annotation>
      <documentation>avgrensningslinje for areal med evaluering av risiko for kvikkleireskred basert på skadekonsekvens og faregrad


-- Definition --
line delimiting area for which quick clay slide hazard has been evaluated based on damage consequences and degree of hazard</documentation>
    </annotation>
  </element>
  <complexType name="KvikkleireFaresoneAvgrType">
    <complexContent>
      <extension base="gml:AbstractFeatureType">
        <sequence>
          <element name="grense" type="gml:CurvePropertyType">
            <annotation>
              <documentation>forløp som følger overgang mellom ulike fenomener

-- Definition --
course following the transition between different real world phenomena</documentation>
            </annotation>
          </element>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="KvikkleireFaresoneAvgrPropertyType">
    <sequence minOccurs="0">
      <element ref="dataleveransebasertpasosidatamodell:KvikkleireFaresoneAvgr"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <element abstract="true" name="NVEFellesegenskaper" substitutionGroup="gml:AbstractFeature" type="dataleveransebasertpasosidatamodell:NVEFellesegenskaperType">
    <annotation>
      <documentation>abstrakt objekt som bærer en rekke egenskaper som er fagområde-uavhengige og kan benyttes for alle objekttyper

Merknad:
Spesielt i produktspesifikasjonsarbeid vil en velge egenskaper og av grensningslinjer fra denne klassen.</documentation>
    </annotation>
  </element>
  <complexType abstract="true" name="NVEFellesegenskaperType">
    <complexContent>
      <extension base="gml:AbstractFeatureType">
        <sequence>
          <element name="identifikasjon" type="dataleveransebasertpasosidatamodell:IdentifikasjonPropertyType">
            <annotation>
              <documentation>abstrakt objekt som bærer en rekke egenskaper som er fagområde-uavhengige og kan benyttes for alle objekttyper

Merknad:
Spesielt i produktspesifikasjonsarbeid vil en velge egenskaper og av grensningslinjer fra denne klassen.</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">IDENT</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element minOccurs="0" name="datauttaksdato" type="date">
            <annotation>
              <documentation>dato for uttak fra en database

Merknad:
Skiller seg fra Kopidato ved at en ikke skiller på om det er uttak fra en originaldatabase eller en kopidatabase.</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">DATAUTTAKSDATO</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element minOccurs="0" name="datafangstdato" type="date">
            <annotation>
              <documentation>dato når objektet siste gang ble registrert/observert/målt i terrenget

Merknad: I mange tilfeller er denne forskjellig fra Oppdateringsdato, da registrerte endringer kan bufres i en kortere eller lengre periode før disse legges inn i databasen.
Ved førstegangsregistrering settes Datafangstdato lik førsteDatafangstdato.</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">DATAFANGSTDATO</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element minOccurs="0" name="førsteDigitaliseringsdato" type="date">
            <annotation>
              <documentation>dato når en representasjon av objektet i digital form første gang ble etablert

Merknad:
førsteDigitaliseringsdato kan skille seg fra førsteDatafangstdato ved at den første datafangsten skjedde analogt og gjort om til digital form senere i en produksjonsprosess.
Eventuelt at innlegging i databasen skjedde på et senere tidspunkt enn registreringen /observasjonen / målingen av objektet.</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">FØRSTEDIGITALISERINGSDATO</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element minOccurs="0" name="oppdateringsdato" type="date">
            <annotation>
              <documentation>dato for siste endring på objektetdataene

Merknad:
Oppdateringsdato kan være forskjellig fra Datafangsdato ved at data som er registrert kan bufres en kortere eller lengre periode før disse legges inn i datasystemet (databasen).

-Definition-
Date and time at which this version of the spatial object was inserted or changed in the spatial data set.</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">OPPDATERINGSDATO</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element minOccurs="0" name="opphav" type="string">
            <annotation>
              <documentation>referanse til opphavsmaterialet, kildematerialet, organisasjons/publiseringskilde

Merknad:
Kan også beskrive navn på person og årsak til oppdatering</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">OPPHAV</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="NVEFellesegenskaperPropertyType">
    <sequence minOccurs="0">
      <element ref="dataleveransebasertpasosidatamodell:NVEFellesegenskaper"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <simpleType name="Prosjektstatus_NVEType">
    <annotation>
      <documentation>Kodeliste for prosjektstatus brukt i NVE</documentation>
    </annotation>
    <union memberTypes="dataleveransebasertpasosidatamodell:Prosjektstatus_NVEEnumerationType dataleveransebasertpasosidatamodell:Prosjektstatus_NVEOtherType"/>
  </simpleType>
  <simpleType name="Prosjektstatus_NVEEnumerationType">
    <annotation>
      <documentation>Kodeliste for prosjektstatus brukt i NVE</documentation>
    </annotation>
    <restriction base="string">
      <enumeration value="utført">
        <annotation>
          <documentation>Nei</documentation>
        </annotation>
      </enumeration>
      <enumeration value="til ny vurdering">
        <annotation>
          <documentation>Ja</documentation>
        </annotation>
      </enumeration>
      <enumeration value="erstattet av ny">
        <annotation>
          <documentation>Nei</documentation>
        </annotation>
      </enumeration>
      <enumeration value="fjernet">
        <annotation>
          <documentation>Nei</documentation>
        </annotation>
      </enumeration>
      <enumeration value="ajourført">
        <annotation>
          <documentation>Nei</documentation>
        </annotation>
      </enumeration>
      <enumeration value="under planlegging">
        <annotation>
          <documentation>Nei</documentation>
        </annotation>
      </enumeration>
      <enumeration value="pågående">
        <annotation>
          <documentation>Nei</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Ja"/>
      <enumeration value="Nei"/>
    </restriction>
  </simpleType>
  <simpleType name="Prosjektstatus_NVEOtherType">
    <restriction base="string">
      <pattern value="other: \w{2,}"/>
    </restriction>
  </simpleType>
  <simpleType name="SkredFaregradKlasseType">
    <annotation>
      <documentation>graden av sannsynlighet for at det skal gå et skred

Merknad: Gjenspeiler graden av usikkerhet med hensyn til områdets stabilitet basert på topografiske forhold, geologiske/geotekniske forhold og erosjonsforhold. Skredfaregradklassen er basert på en evaluering av faregrad som fremkommer av at ulike vektede faktorer gir en faregradscore (0-51)


-- Definition - -
the degree of probability that there will be an landslide
Note: Reflects the degree of hazard as regards the area's stability, based upon topographic conditions, geological/geotechnical conditions and erosion conditions. The landslideHazardLevelClass is based a weighed hazardfactorscore (0-51</documentation>
    </annotation>
    <union memberTypes="dataleveransebasertpasosidatamodell:SkredFaregradKlasseEnumerationType dataleveransebasertpasosidatamodell:SkredFaregradKlasseOtherType"/>
  </simpleType>
  <simpleType name="SkredFaregradKlasseEnumerationType">
    <annotation>
      <documentation>graden av sannsynlighet for at det skal gå et skred

Merknad: Gjenspeiler graden av usikkerhet med hensyn til områdets stabilitet basert på topografiske forhold, geologiske/geotekniske forhold og erosjonsforhold. Skredfaregradklassen er basert på en evaluering av faregrad som fremkommer av at ulike vektede faktorer gir en faregradscore (0-51)


-- Definition - -
the degree of probability that there will be an landslide
Note: Reflects the degree of hazard as regards the area's stability, based upon topographic conditions, geological/geotechnical conditions and erosion conditions. The landslideHazardLevelClass is based a weighed hazardfactorscore (0-51</documentation>
    </annotation>
    <restriction base="string">
      <enumeration value="Ingen">
        <annotation>
          <documentation>Påvist ikkje kvikkleire/sprøbruddmateriale, eller topografiske forhold som tilsier at kvikkleireskred ikke kan forekomme</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Lav">
        <annotation>
          <documentation>Gunstige topografiske forhold.  Grunnundersøkelser viser at grunnforholdene er akseptable.  Det er lite eller ingen aktiv erosjon i vassdraget.  Det har vært liten skredaktivitet i området.  Ingen terrenginngrep, terrenginngrep har hatt gunstig innvirkning på stabiliteten (faregradscore 0-17)</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Middels">
        <annotation>
          <documentation>Mindre gunstig topografiske forhold.  Mangelfulle grunnundersøkelser, eller grunnundersøkelsene viser mindre gunstige grunnforhold.  Det er aktiv erosjon i vassdraget.  Det har vært betydelig skredaktivitet i området.  Eventuelle terrenginngrep har liten eller ingen stabilitetsforverrende virkning (faregradscore 18-25)</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Høy">
        <annotation>
          <documentation>Ugunstige topografiske forhold.  Mangelfulle grunnundersøkelser eller grunnundersøkelsene viser ugunstige grunnforhold.  Det er betydelig aktiv erosjon i vassdraget.  Det har vært stor skredaktivitet i området.  Terrenginngrep med stabilitetsforverrende virkning (faregradscore 26-51)</documentation>
        </annotation>
      </enumeration>
    </restriction>
  </simpleType>
  <simpleType name="SkredFaregradKlasseOtherType">
    <restriction base="string">
      <pattern value="other: \w{2,}"/>
    </restriction>
  </simpleType>
  <element name="SkredFaregrense" substitutionGroup="gml:AbstractFeature" type="dataleveransebasertpasosidatamodell:SkredFaregrenseType">
    <annotation>
      <documentation>grenselinje som viser rekkevidden for mulige skred

Merknad: Resten av faresonepolygonet er ofte avgrenset av dataavgrensningslinje


-- Definition --
boundary line which shows the extent of potential avalanches/landslides</documentation>
    </annotation>
  </element>
  <complexType name="SkredFaregrenseType">
    <complexContent>
      <extension base="gml:AbstractFeatureType">
        <sequence>
          <element name="grense" type="gml:CurvePropertyType">
            <annotation>
              <documentation>forløp som følger overgang mellom ulike fenomener

-- Definition --
course following the transition between different real world phenomena</documentation>
            </annotation>
          </element>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="SkredFaregrensePropertyType">
    <sequence minOccurs="0">
      <element ref="dataleveransebasertpasosidatamodell:SkredFaregrense"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <element abstract="true" name="SkredFareområderFellesegenskaper" substitutionGroup="dataleveransebasertpasosidatamodell:NVEFellesegenskaper" type="dataleveransebasertpasosidatamodell:SkredFareområderFellesegenskaperType">
    <annotation>
      <documentation>abstrakt objekt som bærer en egenskaper som benyttes i flere av fareområdeklassene. Benyttes til arv av egenskaper.</documentation>
    </annotation>
  </element>
  <complexType abstract="true" name="SkredFareområderFellesegenskaperType">
    <complexContent>
      <extension base="dataleveransebasertpasosidatamodell:NVEFellesegenskaperType">
        <sequence>
          <element minOccurs="0" name="prosjektURL" type="string">
            <annotation>
              <documentation>URL-lenke til kartleggingsprosjektets informasjonsside</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">PROSJEKTURL</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element minOccurs="0" name="rapportURL" type="string">
            <annotation>
              <documentation>URL-lenke til rapport fra kartleggingsprosjektet</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">RAPPORTURL</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="SkredFareområderFellesegenskaperPropertyType">
    <sequence minOccurs="0">
      <element ref="dataleveransebasertpasosidatamodell:SkredFareområderFellesegenskaper"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <element name="SkredFaresone" substitutionGroup="dataleveransebasertpasosidatamodell:NVEFellesegenskaper" type="dataleveransebasertpasosidatamodell:SkredFaresoneType">
    <annotation>
      <documentation>område hvor skredfaren er nærmere vurdert/kartlagt med hensyn til sannsynlighet og rekkevidde

Merknad: Skredfaresonen kan bestå av utløsningsområde og utløpsområde for skred


-- Definition --
area where the avalanche/landslide hazard has been evaluated/surveyed in more detail with regard to probability and extent</documentation>
    </annotation>
  </element>
  <complexType name="SkredFaresoneType">
    <complexContent>
      <extension base="dataleveransebasertpasosidatamodell:NVEFellesegenskaperType">
        <sequence>
          <element name="område" type="gml:SurfacePropertyType">
            <annotation>
              <documentation>objektets utstrekning

-- Definition --
area over which an object extends</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">Flate</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element name="skredtype" type="dataleveransebasertpasosidatamodell:SkredtypeDetaljertType">
            <annotation>
              <documentation>hvilke skredmasser som er forbundet med skredfaren eller skredhendelsen

Merknad: Ulike typer skredmasser som bl.a. stein, snø, fjell, jord og kombinasjoner av disse

-- Definition --
what type of avalanche/landslide masses related to the avalanche/landslide hazard or event
Note: Various types of avalanche/landslide masses, such as rock, snow, soil and combinations these</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">SKREDTYPE</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element name="skredStatistikkSannsynlighet" type="dataleveransebasertpasosidatamodell:SkredSannsynlighetType">
            <annotation>
              <documentation>statistisk sannsynlighet for at det går et skred

Betingelse: Egenskapen skredFaregradKlasse eller skredStatistikkSannsynlighet er påkrevet. skredFaregradKlasse benyttes ved kvikkleire og skredStatistikkSannsynlighet ved bratt terreng

Merknad: Oppgis som et skred per antall år. I plan og bygningsloven skal man ta hensyn til 1000 årsskredet.

-- Definition --
statistical probability that an avalanche  landslide will take place   Condition: The attribute landslideHazardLevelClass or avalancheStatisticProbability is mandatory. landslideHazardLevelClass is used in the case of quick clay and avalancheStatisticProbability in the case of steep terrain   Note:  Indicated as a yearly probability of avalanches/landslides. In the Planning and Building Act consideration must be given for the yearly probability of 1/1000</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">SKREDSTATSANN</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element maxOccurs="unbounded" name="skredFaregrense" type="dataleveransebasertpasosidatamodell:SkredFaregrensePropertyType"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="SkredFaresonePropertyType">
    <sequence minOccurs="0">
      <element ref="dataleveransebasertpasosidatamodell:SkredFaresone"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <simpleType name="SkredKvalKartleggingType">
    <annotation>
      <documentation>status og detaljeringsgrad vedrørende kartleggingsarbeidet


-- Definition - -
status, quality and degree of detail regarding the mapping work</documentation>
    </annotation>
    <union memberTypes="dataleveransebasertpasosidatamodell:SkredKvalKartleggingEnumerationType dataleveransebasertpasosidatamodell:SkredKvalKartleggingOtherType"/>
  </simpleType>
  <simpleType name="SkredKvalKartleggingEnumerationType">
    <annotation>
      <documentation>status og detaljeringsgrad vedrørende kartleggingsarbeidet


-- Definition - -
status, quality and degree of detail regarding the mapping work</documentation>
    </annotation>
    <restriction base="string">
      <enumeration value="Ingen undersøkelse">
        <annotation>
          <documentation>Det er kun topografiske vurderinger som ligger til grunn for
kvikkleirefaresonen, ingen befaring eller grunnundersøkelse. Denne kodeverdien må brukes dersom man skal utveksle soner som ikke er klassifisert</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Enkel undersøkelse">
        <annotation>
          <documentation>Enkel undersøkelse av sonen, oversiktskartlegging

-- Definition --
Simple investigation of the zone, overview mapping.</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Supplerende undersøkelser / stabilitet">
        <annotation>
          <documentation>Utført supplerende undersøkelser og vurdering av stabilitet

-- Definition --
Supplementary investigation and assessment of stability carried out</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Sikringstiltak utført">
        <annotation>
          <documentation>Sikringstiltak er utført</documentation>
        </annotation>
      </enumeration>
    </restriction>
  </simpleType>
  <simpleType name="SkredKvalKartleggingOtherType">
    <restriction base="string">
      <pattern value="other: \w{2,}"/>
    </restriction>
  </simpleType>
  <simpleType name="SkredRisikoKvikkleireKlasseType">
    <annotation>
      <documentation>risikoen for at et område kan bli påført skredskade, inndelt etter risikoklasser

Merknad: Denne egenskapen gjengir en klassifisering av risiko for at området vil bli utsatt for skredskade. Klassifiseringsmetoden er basert på en evaluering av skadekonsekvens og faregrad. Evalueringen foretas ved at det beregnes poeng for hver sone i henhold til utarbeidde klassifiseringskriterier (se kapittel definisjoner og forkortelser.)


-- Definition - -
the risk that a landslide may inflict damage on an area, categorized according to risk classes  Note: This attribute cites a classification of risk that the area will be vulnerable to landslide damage. The classification method is based on a review of damage consequences and hazard levels</documentation>
    </annotation>
    <union memberTypes="dataleveransebasertpasosidatamodell:SkredRisikoKvikkleireKlasseEnumerationType dataleveransebasertpasosidatamodell:SkredRisikoKvikkleireKlasseOtherType"/>
  </simpleType>
  <simpleType name="SkredRisikoKvikkleireKlasseEnumerationType">
    <annotation>
      <documentation>risikoen for at et område kan bli påført skredskade, inndelt etter risikoklasser

Merknad: Denne egenskapen gjengir en klassifisering av risiko for at området vil bli utsatt for skredskade. Klassifiseringsmetoden er basert på en evaluering av skadekonsekvens og faregrad. Evalueringen foretas ved at det beregnes poeng for hver sone i henhold til utarbeidde klassifiseringskriterier (se kapittel definisjoner og forkortelser.)


-- Definition - -
the risk that a landslide may inflict damage on an area, categorized according to risk classes  Note: This attribute cites a classification of risk that the area will be vulnerable to landslide damage. The classification method is based on a review of damage consequences and hazard levels</documentation>
    </annotation>
    <restriction base="string">
      <enumeration value="Risikoklasse 0">
        <annotation>
          <documentation>Områder hvor det ikke er fare for kvikkleireskred.</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Risikoklasse 1">
        <annotation>
          <documentation>Områder hvor det normalt ikke vil være aktuelt å foreta noen form for videre evaluering eller tiltak. Ved et eventuelt anleggsmessig inngrep vil det kreves dokumentasjon på at sikkerheten er tilfredsstillende.

-- Definition --
Areas where any further evaluation or action will normally not be relevant. For any intervention in the form of construction, documentation that safety is satisfactory will be required.</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Risikoklasse 2">
        <annotation>
          <documentation>Som ved risikoklasse 1 vil det heller ikke her  normalt  være aktuelt å foreta noen form for videre evaluering eller tiltak. Ved et eventuelt anleggsmessig inngrep vil det kreves dokumentasjon på at sikkerheten er tilfredsstillende.

-- Definition --
As with Risk Class 1, neither will further evaluation or action normally be relevant here. For any intervention in the form of construction, documentation that safety is satisfactory will be required.</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Risikoklasse 3">
        <annotation>
          <documentation>Omfatter soner med til dels tett bebyggelse.

-- Definition --
Includes zones that may in part be heavily built-up.</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Risikoklasse 4">
        <annotation>
          <documentation>Omfatter for det meste soner med tett bebyggelse. Må gis høy prioritet i det videre arbeidet med sikring mot skred.

-- Definition --
Mainly comprising zones that are heavily built-up. Must be given high priority in the further work on preventive measures against landslide.</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Risikoklasse 5">
        <annotation>
          <documentation>Omfatter soner med høyeste skadekonsekvens og høyeste faregrad. Må gis høy prioritet i det videre arbeidet med sikring mot skred.

-- Definition --
Comprising zones with the greatest injury consequences and highest hazard level. Must be given high priority in the ongoing work of landslide prevention.</documentation>
        </annotation>
      </enumeration>
    </restriction>
  </simpleType>
  <simpleType name="SkredRisikoKvikkleireKlasseOtherType">
    <restriction base="string">
      <pattern value="other: \w{2,}"/>
    </restriction>
  </simpleType>
  <simpleType name="SkredSannsynlighetType">
    <annotation>
      <documentation>sannsynlig gjentaksintervall for skredhendelse i området (antall år)</documentation>
    </annotation>
    <union memberTypes="dataleveransebasertpasosidatamodell:SkredSannsynlighetEnumerationType dataleveransebasertpasosidatamodell:SkredSannsynlighetOtherType"/>
  </simpleType>
  <simpleType name="SkredSannsynlighetEnumerationType">
    <annotation>
      <documentation>sannsynlig gjentaksintervall for skredhendelse i området (antall år)</documentation>
    </annotation>
    <restriction base="string">
      <enumeration value="100">
        <annotation>
          <documentation>Gjentaksintervall: 100 år</documentation>
        </annotation>
      </enumeration>
      <enumeration value="1000">
        <annotation>
          <documentation>Gjentaksintervall: 1000 år</documentation>
        </annotation>
      </enumeration>
      <enumeration value="5000">
        <annotation>
          <documentation>Gjentaksintervall: 5000 år</documentation>
        </annotation>
      </enumeration>
    </restriction>
  </simpleType>
  <simpleType name="SkredSannsynlighetOtherType">
    <restriction base="string">
      <pattern value="other: \w{2,}"/>
    </restriction>
  </simpleType>
  <simpleType name="SkredSkadeKonsekvensKlasseType">
    <annotation>
      <documentation>hvilke økonomiske og samfunnsmessige følger et kvikkleireskred får og fare for tap av menneskeliv

Merknad: Kvalitativ klassifisering av skadekonsekvens i forbindelse med fare for liv, skade på mennesker, økonomiske tap, verdiforringelse samt fare for at viktige samfunnsmessige funksjoner skal stoppe opp. For skredtypen


-- Definition - -
what economic and social consequences follow a quick clay slide, and risk of loss of human lives  Note: Qualitative classification of damage consequence in connection with risk of fatalities, personal injuries, financial loss, value reduction as well as the risk that  important social functions can be affected</documentation>
    </annotation>
    <union memberTypes="dataleveransebasertpasosidatamodell:SkredSkadeKonsekvensKlasseEnumerationType dataleveransebasertpasosidatamodell:SkredSkadeKonsekvensKlasseOtherType"/>
  </simpleType>
  <simpleType name="SkredSkadeKonsekvensKlasseEnumerationType">
    <annotation>
      <documentation>hvilke økonomiske og samfunnsmessige følger et kvikkleireskred får og fare for tap av menneskeliv

Merknad: Kvalitativ klassifisering av skadekonsekvens i forbindelse med fare for liv, skade på mennesker, økonomiske tap, verdiforringelse samt fare for at viktige samfunnsmessige funksjoner skal stoppe opp. For skredtypen


-- Definition - -
what economic and social consequences follow a quick clay slide, and risk of loss of human lives  Note: Qualitative classification of damage consequence in connection with risk of fatalities, personal injuries, financial loss, value reduction as well as the risk that  important social functions can be affected</documentation>
    </annotation>
    <restriction base="string">
      <enumeration value="Ikke alvorlig"/>
      <enumeration value="Mindre alvorlig">
        <annotation>
          <documentation>Liten risiko for skade på mennesker, tap av liv, begrensede økonomiske og samfunnsmessige konsekvenser (0-6 poeng).

-- Definition --
Low risk of personal injuries, loss of life; limited economic and social consequences (0-6 points).</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Alvorlig">
        <annotation>
          <documentation>Risiko for skade på mennesker/tap av liv eller betydelige økonomiske og samfunnsmessige konsekvenser (7-22 poeng).

-- Definition --
Risk of personal injuries/loss of life or substantial economic and social consequences (7-22 points).</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Meget alvorlig">
        <annotation>
          <documentation>Stor risiko for skade på mennesker/tap av liv eller meget store økonomiske og samfunnsmessige konsekvenser (23-45 poeng).

-- Definition --
High risk of personal injuries/loss of life or very great economic and social consequences (23-45 points).</documentation>
        </annotation>
      </enumeration>
    </restriction>
  </simpleType>
  <simpleType name="SkredSkadeKonsekvensKlasseOtherType">
    <restriction base="string">
      <pattern value="other: \w{2,}"/>
    </restriction>
  </simpleType>
  <element name="SkredTypePunkt" substitutionGroup="dataleveransebasertpasosidatamodell:NVEFellesegenskaper" type="dataleveransebasertpasosidatamodell:SkredTypePunktType">
    <annotation>
      <documentation>Punkt som definerer den dimensjonerende skredtypen for en eller flere faresoner.</documentation>
    </annotation>
  </element>
  <complexType name="SkredTypePunktType">
    <complexContent>
      <extension base="dataleveransebasertpasosidatamodell:NVEFellesegenskaperType">
        <sequence>
          <element name="punkt" type="gml:PointPropertyType">
            <annotation>
              <documentation>sted som objektet eksisterer på</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">PUNKT</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element name="skredOmrID" type="integer">
            <annotation>
              <documentation>unikt id-nummer for skredområde/kvikkleirefaresone

-- Definition --
unique ID number for landslide area or quick clay hazard zone</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">SKREDOMRID</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element name="skredtype" type="dataleveransebasertpasosidatamodell:SkredtypeDetaljertType">
            <annotation>
              <documentation>hvilke skredmasser som er forbundet med skredfaren eller skredhendelsen

Merknad: Ulike typer skredmasser som bl.a. stein, snø, fjell, jord og kombinasjoner av disse

-- Definition --
what type of avalanche/landslide masses related to the avalanche/landslide hazard or event
Note: Various types of avalanche/landslide masses, such as rock, snow, soil and combinations these</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">SKREDTYPE</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="SkredTypePunktPropertyType">
    <sequence minOccurs="0">
      <element ref="dataleveransebasertpasosidatamodell:SkredTypePunkt"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <simpleType name="SkredtypeDetaljertType">
    <annotation>
      <documentation>hvilke skredmasser som er forbundet med skredfaren eller skredhendelsen

Merknad 1: Ulike typer skredmasser som bl.a. stein, snø, fjell, jord og kombinasjoner av disse
Merknad 2: Denne kodelisten er mer detaljert enn Skredtype definert i SOSI-standarden SKRED


-- Definition - -
what type of avalanche/landslide masses related to  the avalanche/landslide hazard or event  Note: Various types of avalanche/landslide masses, such as rock, snow, soil and combinations of these</documentation>
    </annotation>
    <union memberTypes="dataleveransebasertpasosidatamodell:SkredtypeDetaljertEnumerationType dataleveransebasertpasosidatamodell:SkredtypeDetaljertOtherType"/>
  </simpleType>
  <simpleType name="SkredtypeDetaljertEnumerationType">
    <annotation>
      <documentation>hvilke skredmasser som er forbundet med skredfaren eller skredhendelsen

Merknad 1: Ulike typer skredmasser som bl.a. stein, snø, fjell, jord og kombinasjoner av disse
Merknad 2: Denne kodelisten er mer detaljert enn Skredtype definert i SOSI-standarden SKRED


-- Definition - -
what type of avalanche/landslide masses related to  the avalanche/landslide hazard or event  Note: Various types of avalanche/landslide masses, such as rock, snow, soil and combinations of these</documentation>
    </annotation>
    <restriction base="string">
      <enumeration value="Steinskred, uspesifisert">
        <annotation>
          <documentation>Steinskred, ikke nærmere bestemt type</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Steinsprang (&lt; 100 m3)">
        <annotation>
          <documentation>Steinsprang (steinblokker &lt; 100 m3)</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Lite fjellskred (100 - 10 000 m3)">
        <annotation>
          <documentation>Lite fjellskred (steinblokker 100 - 10 000 m3)</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Fjellskred (&gt; 10 000 m3)">
        <annotation>
          <documentation>Fjellskred (steinblokker &gt; 10 000 m3)</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Undervannsskred, uspesifisert">
        <annotation>
          <documentation>Undervannsskred, ikke nærmere bestemt type</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Snøskred, uspesifisert">
        <annotation>
          <documentation>Snøskred, ikke nærmere bestemt type</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Vått snøskred"/>
      <enumeration value="Tørt snøskred"/>
      <enumeration value="Sørpeskred"/>
      <enumeration value="Løssnøskred, uspesifisert">
        <annotation>
          <documentation>Løssnøskred, ikke nærmere bestemt type</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Vått løssnøskred"/>
      <enumeration value="Tørt løssnøskred"/>
      <enumeration value="Flakskred, uspesifisert">
        <annotation>
          <documentation>Flakskred, ikke nærmere bestemt type</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Vått flakskred"/>
      <enumeration value="Tørt flakskred"/>
      <enumeration value="Løsmasseskred, uspesifisert">
        <annotation>
          <documentation>Løsmasseskred, ikke nærmere bestemt type</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Kvikkleireskred"/>
      <enumeration value="Flomskred"/>
      <enumeration value="Leirskred"/>
      <enumeration value="Jordskred"/>
      <enumeration value="Jordskred, uspesifisert">
        <annotation>
          <documentation>Jordskred, ikke nærmere bestemt type

Merknad: Fra og med 2015 benyttes ikke denne verdien for nye data.</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Isnedfall, uspesifisert">
        <annotation>
          <documentation>Isnedfall, ikke nærmere bestemt type</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Skavlfall"/>
      <enumeration value="Utglidning av veg"/>
      <enumeration value="Ikke angitt">
        <annotation>
          <documentation>Skredtype ikke angitt</documentation>
        </annotation>
      </enumeration>
      <enumeration value="Ny, ikke-godkjent skredtype">
        <annotation>
          <documentation>Ny, ikke-godkjent skredtype

Merknad: Fra og med 2015 benyttes ikke denne verdien for nye data.</documentation>
        </annotation>
      </enumeration>
    </restriction>
  </simpleType>
  <simpleType name="SkredtypeDetaljertOtherType">
    <restriction base="string">
      <pattern value="other: \w{2,}"/>
    </restriction>
  </simpleType>
  <element name="UtlopOmr" substitutionGroup="dataleveransebasertpasosidatamodell:KvikkleireFaresone" type="dataleveransebasertpasosidatamodell:UtlopOmrType">
    <annotation>
      <documentation>areal som påvirkes eller dekkes av skredmassser når skred utløses


-- Definition --
area which is affected or covered by avalanche/landslide masses when an avalanche/landslide occurs</documentation>
    </annotation>
  </element>
  <complexType name="UtlopOmrType">
    <complexContent>
      <extension base="dataleveransebasertpasosidatamodell:KvikkleireFaresoneType">
        <sequence>
          <element maxOccurs="unbounded" name="kvikkleireFaresoneAvgr" type="dataleveransebasertpasosidatamodell:KvikkleireFaresoneAvgrPropertyType"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="UtlopOmrPropertyType">
    <sequence minOccurs="0">
      <element ref="dataleveransebasertpasosidatamodell:UtlopOmr"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <element name="UtlosningOmr" substitutionGroup="dataleveransebasertpasosidatamodell:KvikkleireFaresone" type="dataleveransebasertpasosidatamodell:UtlosningOmrType">
    <annotation>
      <documentation>område hvor skred kan utløses

Merknad: Alle typer skred</documentation>
    </annotation>
  </element>
  <complexType name="UtlosningOmrType">
    <complexContent>
      <extension base="dataleveransebasertpasosidatamodell:KvikkleireFaresoneType">
        <sequence>
          <element maxOccurs="unbounded" name="kvikkleireFaresoneAvgr" type="dataleveransebasertpasosidatamodell:KvikkleireFaresoneAvgrPropertyType"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="UtlosningOmrPropertyType">
    <sequence minOccurs="0">
      <element ref="dataleveransebasertpasosidatamodell:UtlosningOmr"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
</schema>
